### ISSUE TITLE
22/jul/Morning Session

### ISSUE THREAD

**Issue by VictorOmarT** [VictorOmarT/Bootstrap-exercise#1]

**Comment by AlexHamn** [comment]
https://github.com/VictorOmarT/Bootstrap-exercise/blob/2b70162393dbaf9b9f6be3a932f3332d1b508216/main.scss#L13

It seems like you never get around to use this line of code; you may want to consider deleting it.

**Comment by Hamzaoutdoors** [comment]
https://github.com/VictorOmarT/Bootstrap-exercise/blob/2b70162393dbaf9b9f6be3a932f3332d1b508216/index.html#L78-L104

- [ ]  you can work with Bootstrap 5.0 cards to create cards for your website
